# Generated by Django 3.1 on 2019-12-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.CharField(max_length=200)),
                ('Shift', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=200)),
                ('Age', models.CharField(max_length=200)),
                ('Furcolor', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Speci_loc', models.CharField(max_length=200)),
                ('Other_act', models.CharField(max_length=200)),
            ],
        ),
    ]
